; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
description = OSSM M5 Remote Redux
data_dir = data
default_envs = m5stack-cores3

[project_metadata]
display_name = OSSM M5 Remote Redux
artifact_name = OSSM-M5-Remote-Redux
version = 0.1.0-dev
default_charge_current_ma = 500

[env]
platform = espressif32@7.0.1
framework = arduino
extra_scripts = 
    pre:scripts/build_config.py
    post:scripts/merge_bin.py
    post:scripts/package_firmware.py
monitor_speed = 115200
upload_protocol = esptool
board_build.partitions = default_16MB.csv
lib_deps =
    m5stack/M5Unified@0.2.17
    m5stack/M5GFX@0.2.24
    madhephaestus/ESP32Encoder@0.12.0
    mathertel/OneButton@2.6.2
    lvgl/lvgl@9.5.0
    h2zero/NimBLE-Arduino@2.5.0
    bblanchon/ArduinoJson@7.4.3
build_flags = 
    -D BUILD_TARGET=\"$PIOENV\"
    -D CORE_DEBUG_LEVEL=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I src




[env:m5stack-core2]
board = m5stack-core2
build_flags = 
     ${env.build_flags}



[env:m5stack-cores3]
board = m5stack-cores3
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes
build_flags =
     -D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1   
     ${env.build_flags}

;upload_port = com7
;monitor_port = com7
